<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE events [
<!ELEMENT event (theme?,organization?,place?,year?)>
<!ELEMENT theme (#PCDATA)>
<!ELEMENT organization (#PCDATA)>
<!ELEMENT place (#PCDATA)>
<!ELEMENT year (#PCDATA)>
]>
<events>
	<event>
		<theme>ESACH at the Science Festival “Science Spring” of Opole University.</theme>
		<organization>ESACH OPOLE</organization>
		<year>2019</year>
	</event>
    <event>
		<theme>Conference on Cultural Heritage in Europee.</theme>
		<organization>ESACH Madrid</organization>
        <place>Madrid</place>
		<year>2019</year>
	</event>
    <event>
		<theme>My culture + your culture = world culture ?!</theme>
		<organization>ESACH Passau</organization>
        <place>Passau</place>
		<year>2019</year>
	</event>
    <event>
		<theme>Second ESACH Meeting – Event ESACH Meeting Genoa 2019.</theme>
		<organization>ESACH Genoa</organization>
        <place>Genoa</place>
		<year>2019</year>
	</event>
    <event>
		<theme>ESACH Meeting 2018</theme>
		<organization>ESACH Girona</organization>
        <place>Girona</place>
		<year>2018</year>
	</event>
    <event>
		<theme>Student Summit</theme>
        <place>Berlin</place>
		<year>2018</year>
	</event>
    <event>
		<theme>ESACH Message at the Conferences about Intangible Cultural Heritage organized by FACYDE.</theme>
		<organization>ESACH Madrid</organization>
        <place>Murcia</place>
		<year>2018</year>
	</event>
</events>